"""Mark done -> re-run the analysis -> it must still be done.

This guards the one bug that would discredit the whole app. Commitment rows are
regenerated by every run, so if completion lived on them a finished task would
march back onto the board the next time the pipeline ran.
"""

from __future__ import annotations

import pytest

from app.db.repositories import CompletionRepository, MessageRepository, UserRepository
from app.services.radar import run_analysis
from tests.fakes import StubCommitmentEngine


async def _analyse(session_factory, user_id, settings, *, with_marks: bool = True):
    async with session_factory() as db:
        users = UserRepository(db)
        user = await users.get_by_id(user_id)
        threads = await MessageRepository(db).threads_for_user(user_id)
        completions = CompletionRepository(db)
        marks = await completions.marks_for_user(user_id) if with_marks else {}
        by_thread = await completions.marks_by_thread(user_id) if with_marks else {}

        return await run_analysis(
            engine=StubCommitmentEngine(),
            threads=threads,
            identity=users.identity_of(user),
            now=settings.now(),
            completion_marks=marks,
            completion_marks_by_thread=by_thread,
        )


@pytest.mark.asyncio
async def test_completion_survives_reanalysis(session_factory, seeded_user, settings):
    first = await _analyse(session_factory, seeded_user, settings)
    target = next(i.commitment for i in first.scored if "MSA redlines" in i.commitment.task)
    board_before = sum(1 for i in first.scored if i.commitment.is_actionable)

    async with session_factory() as db:
        await CompletionRepository(db).mark(seeded_user, target.key, target.thread_key)
        await db.commit()

    second = await _analyse(session_factory, seeded_user, settings)
    same = next(i.commitment for i in second.scored if i.commitment.key == target.key)

    assert same.is_user_completed, "the mark did not survive re-analysis"
    assert same.is_actionable is False, "it is back on the board"
    assert sum(1 for i in second.scored if i.commitment.is_actionable) == board_before - 1


@pytest.mark.asyncio
async def test_key_is_recomputed_identically_by_a_fresh_run(session_factory, seeded_user, settings):
    """The mechanism the test above relies on: keys are stable, not incidental."""
    first = await _analyse(session_factory, seeded_user, settings)
    second = await _analyse(session_factory, seeded_user, settings)
    assert {i.commitment.key for i in first.scored} == {i.commitment.key for i in second.scored}


@pytest.mark.asyncio
async def test_completed_work_is_hidden_from_the_prioritisation_stage(
    session_factory, seeded_user, settings
):
    """Marks apply between the stages, so the briefing cannot suggest done work."""
    first = await _analyse(session_factory, seeded_user, settings)
    target = next(i.commitment for i in first.scored if "MSA redlines" in i.commitment.task)

    async with session_factory() as db:
        await CompletionRepository(db).mark(seeded_user, target.key, target.thread_key)
        await db.commit()

    second = await _analyse(session_factory, seeded_user, settings)
    ranked = {i.commitment.key for i in second.scored if i.priority.rationale}
    assert target.key not in ranked, "a completed item was still sent to be ranked"


@pytest.mark.asyncio
async def test_unmark_returns_it_to_the_board(session_factory, seeded_user, settings):
    first = await _analyse(session_factory, seeded_user, settings)
    target = next(i.commitment for i in first.scored if "MSA redlines" in i.commitment.task)

    async with session_factory() as db:
        completions = CompletionRepository(db)
        await completions.mark(seeded_user, target.key, target.thread_key)
        await db.commit()
        await completions.unmark(seeded_user, target.key)
        await db.commit()

    again = await _analyse(session_factory, seeded_user, settings)
    restored = next(i for i in again.scored if i.commitment.key == target.key)
    assert restored.commitment.is_actionable
    assert restored.bucket == "this_week"


@pytest.mark.asyncio
async def test_marking_is_idempotent(session_factory, seeded_user, settings):
    """A double-submitted form must not create two rows."""
    async with session_factory() as db:
        completions = CompletionRepository(db)
        await completions.mark(seeded_user, "some-key", "some-thread")
        await completions.mark(seeded_user, "some-key", "some-thread")
        await db.commit()
        assert len(await completions.marks_for_user(seeded_user)) == 1


@pytest.mark.asyncio
async def test_marks_do_not_leak_between_users(session_factory, seeded_user, settings):
    async with session_factory() as db:
        other = await UserRepository(db).create(
            email="other@example.com", password_hash="x", display_name="Other",
            aliases=[], alt_emails=[], projects=[],
        )
        completions = CompletionRepository(db)
        await completions.mark(seeded_user, "shared-key", "shared-thread")
        await db.commit()
        assert await completions.marks_for_user(other.id) == {}
